---
title: "Project_Allocation"
author: "Badal Singh"
date: "9/26/2018"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
library(ggplot2)
df = data.frame(read.csv('./project_aloc.csv',header = TRUE,sep = ','))
```

## Project allocation
This graph shows number of project a resource worked on, with color coded projects.
```{r echo=FALSE}
g <- ggplot(df,aes(x=df$Resource_Name))+geom_bar()
#g+ geom_bar(aes(weight=df$Hours.week))
g+geom_bar(aes(fill = Project))+xlab("Resource Name")+ylab("Number of projects")
```

## Hours spent on projects
Graph to represent hours/week allocation for each resource accumulatively and per project.
```{r echo=FALSE}
max_hour <- data.frame(aggregate(Hours.week ~ Resource_Name,df,sum))
m_h <- max(max_hour$Hours.week) + 10
ggplot(df,aes(x=df$Resource_Name,y=df$Hours.week,label=df$Hours.week))+geom_bar(stat = 'identity',aes(fill=Project))+xlab("Resource Name")+ylab("Hours/Week for a Project")+scale_y_continuous(breaks=seq(0,50,5))
```

## Some cool statistics

```{r echo=FALSE}
lvls <- levels(as.factor(max_hour$Resource_Name))

#Employees with maximum hours/week allocation
max_hr <- subset(max_hour,max_hour$Hours.week == max(max_hour$Hours.week))

#Employees with minimum hours/week allocation
min_hr <- subset(max_hour,max_hour$Hours.week == min(max_hour$Hours.week))

#Employees with maximum hours/week allocation
for(row in 1:nrow(max_hr)){
  cat("Employee with maximum hours per week allocation is",lvls[max_hr[row,1]],"with",max_hr[row,2],"hours/week\n")
  
}

#Employees with minimum hours/week allocation
for(row in 1:nrow(min_hr)){
  cat("Employee with minimum hours per week allocation is",lvls[min_hr[row,1]],"with",min_hr[row,2],"hours/week\n")
  
}

cat("Average hours/week allocation for the team is",mean(max_hour$Hours.week),"hours/week")
```



